# Jekyll Uno configurations
# ==========================

# Site settings
title: 'Renato Cordeiro'
description: 'Programmer - Researcher - Geek'
url: 'https://renatocf.github.io'
baseurl: '/'
google_analytics: 'UA-90809972-1'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Renato Cordeiro Ferreira'
  email: renatocf@ime.usp.br
  twitter_username: renatocf_
  facebook_username: RenatoCordeiroFerreira
  github_username:  renatocf
  gitlab_username:  renatocf
  linkedin_username:  renatocordeiroferreira

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
